{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    "app.kubernetes.io/name": {{ template "pyspark-notebook.name" . }}
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}
    "app.kubernetes.io/instance": {{ .Release.Name }}
    "app.kubernetes.io/version": {{ .Chart.AppVersion }}
  name: {{ template "pyspark-notebook.configMap.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  "jupyter_notebook_config.py": |-
    {{ .Files.Get "jupyter_notebook_config.py" }}
{{- end -}}