apiVersion: v1
kind: Service
metadata:
  labels:
    "app.kubernetes.io/name": {{ template "pyspark-notebook.name" . }}
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}
    "app.kubernetes.io/instance": {{ .Release.Name }}
    "app.kubernetes.io/version": {{ .Chart.AppVersion }}
  name: {{ template "pyspark-notebook.fullname" . }}-spark-driver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    sparkRole: driver
    "app.kubernetes.io/instance": {{ .Release.Name }}
  clusterIP: None